<?xml version="1.0"?>
<package format="3">
  <name>robocup_home_navigation</name>
  <version>0.1.0</version>
  <description>建图、定位、Nav2 和固定地点导航。</description>
  <maintainer email="jb6396892-byte@users.noreply.github.com">SEU RoboCup Home Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
