<?xml version="1.0"?>
<package format="3">
  <name>robocup_home_manipulation</name>
  <version>0.1.0</version>
  <description>MoveIt、抓取、抬升、放置和结果验证。</description>
  <maintainer email="jb6396892-byte@users.noreply.github.com">SEU RoboCup Home Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>robocup_home_interfaces</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
