<?xml version="1.0"?>
<package format="3">
  <name>robocup_home_description</name>
  <version>0.1.0</version>
  <description>TMR 底盘加单 FR3 的比赛整机描述。</description>
  <maintainer email="jb6396892-byte@users.noreply.github.com">SEU RoboCup Home Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>franka_description</exec_depend>
  <exec_depend>franka_hardware</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
